name: "chat.sacha.house"
description: "GL0BALLY_AVAILA8LE_CH4T_R00M - https://chat.sacha.house"
topics: []
homepage: "https://chat.sacha.house"
source:
  provider: github
  namespace: "sachahjkl"
  path: "sachahjkl/chat.sacha.house"
